### ISSUE TITLE
unique id for bets, is returned in answer when param exists

### ISSUE THREAD

**Issue by pharesim** [pharesim/steemdice#2]
current id param becomes ui

**Comment by pharesim** [comment]
create issue in master when done

**Comment by apasia-tech** [comment]
id param becomes ui ? I cant find that issue, please explain more where to navigate.

**Comment by pharesim** [comment]
Oh. Thanks for checking this out, it's basically been solved by including the block ID in the reply.

The param "ui" which is sent by the GUI was called "id" before. I'll close this here.
